src/main/java/com/java/exam/model/Name.java
package com.java.exam.model;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;

public class Name {

	public static final Name EMPTY = new Name("", "", "");
	private final String first;
	private final String middle;
	private final String last;

	public Name(@JsonProperty("first") String first, @JsonProperty("middle") String middle,
			@JsonProperty("last") String last) {
		super();
		this.first = first;
		this.middle = middle;
		this.last = last;
	}

	public String getFirst() {
		return first;
	}

	public String getMiddle() {
		return middle;
	}

	public String getLast() {
		return last;
	}

	@JsonGetter("whole_name")
	public String getWholeName() {
		return first + " " + middle + " " + last;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((first == null) ? 0 : first.hashCode());
		result = prime * result + ((last == null) ? 0 : last.hashCode());
		result = prime * result + ((middle == null) ? 0 : middle.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Name other = (Name) obj;
		if (first == null) {
			if (other.first != null)
				return false;
		} else if (!first.equals(other.first))
			return false;
		if (last == null) {
			if (other.last != null)
				return false;
		} else if (!last.equals(other.last))
			return false;
		if (middle == null) {
			if (other.middle != null)
				return false;
		} else if (!middle.equals(other.middle))
			return false;
		return true;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Name [first=");
		builder.append(first);
		builder.append(", middle=");
		builder.append(middle);
		builder.append(", last=");
		builder.append(last);
		builder.append("]");
		return builder.toString();
	}

}

src/main/java/com/java/exam/model/Profile.java
package com.java.exam.model;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;

public class Profile {

	private final String id;
	private final Boolean active;
	private final Boolean blocked;
	private final String balance;
	private final String picture;
	private final Integer age;
	private final Name name;
	private final String email;
	private final String phone;
	private final String address;
	private final String profile;
	private final long dateRegistered;

	public Profile(@JsonProperty("id") String id, @JsonProperty("active") Boolean active,
			@JsonProperty("blocked") Boolean blocked, @JsonProperty("balance") String balance,
			@JsonProperty("picture") String picture, @JsonProperty("age") Integer age, @JsonProperty("name") Name name,
			@JsonProperty("email") String email, @JsonProperty("phone") String phone,
			@JsonProperty("address") String address, @JsonProperty("profile") String profile,
			@JsonProperty("date_registered") Long dateRegistered) {
		super();
		this.id = id;
		this.active = active;
		this.blocked = blocked;
		this.balance = balance;
		this.picture = picture;
		this.age = age;
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.address = address;
		this.profile = profile;
		this.dateRegistered = dateRegistered;
	}

	public Profile(String id) {
		super();
		this.id = id;
		this.active = false;
		this.blocked = false;
		this.balance = "0";
		this.picture = "";
		this.age = 0;
		this.name = Name.EMPTY;
		this.email = "";
		this.phone = "";
		this.address = "";
		this.profile = "";
		this.dateRegistered = 0L;
	}

	public String getId() {
		return id;
	}

	public Boolean getActive() {
		return active;
	}

	public Boolean getBlocked() {
		return blocked;
	}

	public String getBalance() {
		return balance;
	}

	public String getPicture() {
		return picture;
	}

	public Integer getAge() {
		return age;
	}

	public Name getName() {
		return name;
	}

	public String getEmail() {
		return email;
	}

	public String getPhone() {
		return phone;
	}

	public String getAddress() {
		return address;
	}

	public String getProfile() {
		return profile;
	}

	@JsonGetter("date_registered")
	public long getDateRegistered() {
		return dateRegistered;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Profile other = (Profile) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Profile [id=");
		builder.append(id);
		builder.append(", active=");
		builder.append(active);
		builder.append(", blocked=");
		builder.append(blocked);
		builder.append(", balance=");
		builder.append(balance);
		builder.append(", picture=");
		builder.append(picture);
		builder.append(", age=");
		builder.append(age);
		builder.append(", name=");
		builder.append(name);
		builder.append(", email=");
		builder.append(email);
		builder.append(", phone=");
		builder.append(phone);
		builder.append(", address=");
		builder.append(address);
		builder.append(", profile=");
		builder.append(profile);
		builder.append(", dateRegistered=");
		builder.append(dateRegistered);
		builder.append("]");
		return builder.toString();
	}

}

src/main/java/com/java/exam/controller/ProfileController.java
package com.java.exam.controller;

import java.util.ArrayList;
import javax.servlet.http.HttpServletRequest;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

import com.java.exam.exception.DataNotFoundException;
import com.java.exam.manager.ProfileManager;
import com.java.exam.model.Profile;
 
@Controller
public class ProfileController {

	public static final String PROFILE_LIST_URI = "http://s3-ap-southeast-1.amazonaws.com/fundo/js/profiles.json";

	@RequestMapping("/")
	public ModelAndView homePage() {
		ModelAndView modelAndView = new ModelAndView("index");
		try {
			ArrayList<Profile> profiles = ProfileManager.getProfileList(PROFILE_LIST_URI);
			modelAndView.addObject("profiles", profiles);
			modelAndView.addObject("status_description", "success");
			modelAndView.addObject("status_code", "200");
		} catch (Exception e) {
			System.out.println("ERROR : " + e);
			modelAndView.addObject("status_description", "Internal Error");
			modelAndView.addObject("status_code", "401");
		}

		return modelAndView;
	}

	@RequestMapping(value = "/view")
	public ModelAndView profilePage(HttpServletRequest request) {
		String id = request.getParameter("id");
		ModelAndView modelAndView = new ModelAndView("profile");
		try {
			Profile profile = ProfileManager.getProfile(PROFILE_LIST_URI, new Profile(id));
			modelAndView.addObject("profile", profile);
			modelAndView.addObject("status_description", "success");
			modelAndView.addObject("status_code", "200");
		} catch (DataNotFoundException e) {
			System.out.println("ERROR : " + e);
			modelAndView.addObject("status_description", "Data Not Found");
			modelAndView.addObject("status_code", "400");
		} catch (Exception e) {
			System.out.println("ERROR : " + e);
			modelAndView.addObject("status_description", "Internal Error");
			modelAndView.addObject("status_code", "401");
		}
		return modelAndView;
	}

}

src/main/webapp/WEB-INF/jsp/index.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Home</title>

<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">

<script>
$(document).ready(function() {
    $('#customers').DataTable();
} );

</script>

</head>
<body>
	<div class="container">

		<c:choose>
			<c:when test="${status_code eq '401' }">
				<p>${status_desc }</p>
			</c:when>

			<c:otherwise>
				<table id="customers" class="display" style="width:100%">
					<thead>
						<tr>
							<th>Name</th>
							<th>Age</th>
							<th>Active</th>
							<th>Blocked</th>
						</tr>
					</thead>
					<tbody>
						<c:forEach items="${profiles }" var="profile">
							<tr
								onclick="window.location='http://localhost:8080/profile/view?id=${profile.id}';">
								<td>${profile.name.wholeName }</td>
								<td>${profile.age}</td>
								<td>${profile.active eq true ? '&#9745;' :  '&#9744;'} </td>
								<td>${profile.blocked eq true ? '&#9745;' :  '&#9744;'}</td>
							</tr>
						</c:forEach>

					</tbody>
				</table>
			</c:otherwise>
		</c:choose>


	</div>

</body>
</html>

src/main/webapp/WEB-INF/jsp/profile.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Profile</title>


</head>
<body>

	<c:choose>
		<c:when test="${status_code eq '200' }">
			<div class="container">
				<div class="container1">
					<div class="profile">
						<img src="${profile.picture }" alt="Avatar" style="width: 100%">

					</div>
					<div class="container2">
						<h4>
							<b>${profile.name.wholeName }</b>
						</h4>
					</div>
				</div>

				<br> <br>
				<div class="container2">

					<table>
						<tr>
							<td>ID:</td>
							<td><b>${profile.id }</b></td>
						</tr>
						<tr>
							<td valign="top">Profile:</td>
							<td><b>${profile.profile }</b></td>
						</tr>
						<tr>
							<td>Email:</td>
							<td><b>${profile.email }</b></td>
						</tr>
						<tr>
							<td>Phone:</td>
							<td><b>${profile.phone }</b></td>
						</tr>
						<tr>
							<td>Address:</td>
							<td><b>${profile.address }</b></td>
						</tr>
						<tr>
							<td>Age:</td>
							<td><b>${profile.age }</b></td>
						</tr>

						<tr>
							<td>Balance:</td>
							<td><b>${profile.balance }</b></td>
						</tr>

					</table>

				</div>
			</div>

		</c:when>

		<c:otherwise>
			<p>${status_desc }</p>
		</c:otherwise>
	</c:choose>

</body>
</html>


<style>
.profile {
	box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
	transition: 0.3s;
	width: 100px;
}

.card:hover {
	box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2);
}

.container {
	padding: 2px 16px;
	border: 1px solid black;
}

.container1 {
	padding: 16px 16px;
	display: inline-flex;
}

.container2 {
	padding: 2px 16px;
}
</style>